export const POLYGON_ADDED = 'POLYGON_ADDED';
export const CHANGE_INTERACTION_MODE = 'CHANGE_INTERACTION_MODE';
export const SET_CURRENT_POINT = 'SET_CURRENT_POINT';
export const UPDATE_NEW_POLY_VERTICES = 'UPDATE_NEW_POLY_VERTICES';
export const SET_SELECTED_POLYGON_ID = 'SET_SELECTED_POLYGON_ID';
export const DELETE_POLYGON = 'DELETE_POLYGON';
export const SET_START_POINT = 'SET_START_POINT';
export const SET_DESTINATION_POINT = 'SET_DESTINATION_POINT';
export const UPDATE_SCENE_RECT = 'UPDATE_SCENE_RECT';

export const UPDATE_RUNNING_OPTIONS = 'UPDATE_RUNNING_OPTIONS';

export const SET_FRONTIER = 'SET_FRONTIER';
export const PUSH_FRONTIER = 'PUSH_FRONTIER';
export const POP_FRONTIER = 'POP_FRONTIER';
export const SET_EXPLORED = 'SET_EXPLORED';
export const PUSH_EXPLORED = 'PUSH_EXPLORED';

export const UPDATE_VISIBILITY_MAP = 'UPDATE_VISIBILITY_MAP';
export const UPDATE_SOLUTION = 'UPDATE_SOLUTION';
export const UPDATE_SOLUTION_ANALYTICS = 'UPDATE_SOLUTION_ANALYTICS';

export const UPDATE_POLYGON_TRANSFORM = 'UPDATE_POLYGON_TRANSFORM';
export const ADD_RANDOM_POLYGON_CIRCLE = 'ADD_RANDOM_POLYGON_CIRCLE';