export const POLYGON_ADDED = 'POLYGON_ADDED';
export const CHANGE_INTERACTION_MODE = 'CHANGE_INTERACTION_MODE';
export const SET_CURRENT_POINT = 'SET_CURRENT_POINT';
export const UPDATE_NEW_POLY_VERTICES = 'UPDATE_NEW_POLY_VERTICES';
export const SET_SELECTED_POLYGON_ID = 'SET_SELECTED_POLYGON_ID';
export const DELETE_POLYGON = 'DELETE_POLYGON';
export const SET_START_POINT = 'SET_START_POINT';
export const SET_DESTINATION_POINT = 'SET_DESTINATION_POINT';