export const POLYGON_ADDED = 'POLYGON_ADDED';
export const CHANGE_INTERACTION_MODE = 'CHANGE_INTERACTION_MODE';
export const SET_CURRENT_POINT = 'SET_CURRENT_POINT';
export const UPDATE_NEW_POLY_VERTICES = 'UPDATE_NEW_POLY_VERTICES';