export enum InteractionMode {
    DRAW_POLYGON = 'DRAW_POLYGON',
    DELETE_POLYGON = 'DELETE_POLYGON',
    SELECT = 'SELECT',
    PICK_START = 'PICK_START',
    PICK_DESTINATION = 'PICK_DESTINATION',
    RUN_ALGORITHM = 'RUN_ALGORITHM',
}